### ISSUE TITLE
关于ch4中的makefile

### ISSUE THREAD

**Issue by prio158** [samblg/book-mobile-ml#4]
我使用make命令 无法成功 ，事实上这个文件夹../deps/resunpack/include好像没有

**Comment by flyswimmer** [comment]
@prio158 我也遇到这个问题了，不知道你解决了没呢
@samblg 期望作者大大帮忙解答一下

**Comment by samblg** [comment]
@flyswimmer @prio158 已提交修正

**Comment by flyswimmer** [comment]
> @flyswimmer @prio158 已提交修正

多谢@samblg作者，虽然ch4已经解决了，但是ch8还是用到了resunpack。
在ch8/detector/src/detectNet.cpp中使用了"resunpack/resunpack.hpp"
